### ISSUE TITLE
[Feature Request] unset/set shader all

### ISSUE THREAD

**Issue by killown** [soreau/filters#2]
**Method Registration:**

- `ipc_repo->register_method("wf/filters/set-view-shader-all", ipc_set_view_shader_all);`
  - *Apply shader to all views*

- `ipc_repo->register_method("wf/filters/unset-view-shader-all", ipc_unset_view_shader_all);`
  - *Remove shader from all views*

**Goals:**

- **Set Shader to All Views:** This method allows for setting the shader on all views directly, reducing the need for scripts to handle this task.

- **Unset Shader from All Views:** To efficiently apply a shader only to the focused view, first unset the shader from all views using this method, then apply it to the focused view. This approach minimizes reliance on scripts.

**Comment by soreau** [comment]
Filters is built around ipc and the whole point is to script it. You can already set all views and unset all views in a script, so this is a NAK.
